### ISSUE TITLE
Implement recover password

### ISSUE THREAD

**Issue by nworiekingslee** [faradayafrica/Faraday-frontend#156]
Here's the userflow:

https://www.figma.com/proto/GmdqdKpgeXsuNo7WoF1xNq/User-Interface?page-id=109%3A376&node-id=649%3A6636&viewport=-5205%2C-98%2C0.09&scaling=scale-down-width&starting-point-node-id=649%3A6636

**Comment by devgenix** [comment]
@nworiekingslee 
@jomefavourite 

To my knowledge, this has been implemented and is in production. 

Is there any other pending work to be done on it? I'd like to close the issue as done.

**Comment by jomefavourite** [comment]
I think I worked on it

**Comment by devgenix** [comment]
> I think I worked on it

Yes, thank you. 

I'll close the issue now.
