### ISSUE TITLE
Update our landing page Meta data

### ISSUE THREAD

**Issue by nworiekingslee** [faradayafrica/Faraday-frontend#158]
You can check the meta data on the URl shorter and modify it for the landing page

**Comment by devgenix** [comment]
> Could you please share the link to the URL shorter?

https://link.faraday.africa

**Comment by jomefavourite** [comment]
> > Could you please share the link to the URL shorter?
> 
> https://link.faraday.africa

Please the code repo rather

**Comment by jomefavourite** [comment]
This is how the metadata is currently on https://link.faraday.africa/ :

![image](https://user-images.githubusercontent.com/54733225/194778497-ee56e038-a850-43d6-bcde-275028a28c33.png)

I don't see any og images present @nworiekingslee @devgenix

**Comment by nworiekingslee** [comment]
Here's a link to the repo of the link shorter
https://github.com/faradayafrica/Url-Shortener-Frontend

**Comment by nworiekingslee** [comment]
I am not sure about the og stuff @devgenix

**Comment by jomefavourite** [comment]
The og stuff isn't really important though

**Comment by jomefavourite** [comment]
Just send the 

title:
description:

**Comment by devgenix** [comment]
> The og stuff isn't really important though
> 

It is. 

I didn't add an image to that one but you can. 

Every page should have a title, description and image. The image is basically Faraday logo. The title and description is dependent on the content of the page, especially for discussion pages.

**Comment by jomefavourite** [comment]
> Referenc

The landing page is just a page, I guess the title would be Faraday Africa, but I don't know what you'll like the description should b

**Comment by devgenix** [comment]
@jomefavourite 

Let's leave this for now. 
I'll let you know when the title and description for the landing page are available.

**Comment by jomefavourite** [comment]
> @jomefavourite
> 
> Let's leave this for now. I'll let you know when the title and description for the landing page are available.

Okay

**Comment by devgenix** [comment]
This issue has been fixed by @aybruhm
