### ISSUE TITLE
Fix the undefine for username bug that appears when a new userskips the last SignUp process

### ISSUE THREAD

**Issue by nworiekingslee** [faradayafrica/Faraday-frontend#172]

**Comment by devgenix** [comment]
@nworiekingslee I guess this has been fixed, yes?

**Comment by devgenix** [comment]
> @nworiekingslee I guess this has been fixed, yes?

@nworiekingslee still yet to get a response from you.

**Comment by devgenix** [comment]
Tested and this issue has been fixed.
