### ISSUE TITLE
Fix all alignment problems with the Login and SignUp flow

### ISSUE THREAD

**Issue by nworiekingslee** [faradayafrica/Faraday-frontend#178]
All items should align center

**Comment by DanielUdechukwu** [comment]
@nworiekingslee 
Please, has this been worked on? If not, can it be assigned to me?

**Comment by nworiekingslee** [comment]
@devgenix are we still giving out tickets?

**Comment by devgenix** [comment]
> @devgenix are we still giving out tickets?

What tickets?

**Comment by nworiekingslee** [comment]
Issues, I mean issues, we refer to them as tickets at my place of work

**Comment by nworiekingslee** [comment]
@DanielUdechukwu please check issues from our other projects. We are currently not giving out issues for this project

**Comment by DanielUdechukwu** [comment]
Alright.

**Comment by devgenix** [comment]
@nworiekingslee 
@jomefavourite 

What's the status on this, was it done?

**Comment by devgenix** [comment]
@nworiekingslee I'm yet to get a reply form you.

**Comment by nworiekingslee** [comment]
This was fixed ages ago
