### ISSUE TITLE
Enable a user to close and open his questions - closing a question, blocks new comments into the question

### ISSUE THREAD

**Issue by nworiekingslee** [faradayafrica/Faraday-frontend#183]

**Comment by devgenix** [comment]
@nworiekingslee did you start working on this already?

I want to assign it to @jomefavourite

**Comment by devgenix** [comment]
> @nworiekingslee did you start working on this already?
> 
> I want to assign it to @jomefavourite

@nworiekingslee I'm waiting for your reply on this.

**Comment by jomefavourite** [comment]
I don't understand the task here

**Comment by devgenix** [comment]
I explained this in the Standup meeting last week, it's the same thing.

Do you still need me to explain it?

**Comment by nworiekingslee** [comment]
I have taken this issue

**Comment by devgenix** [comment]
> I have taken this issue

What's the status on this?

**Comment by nworiekingslee** [comment]
This have been completed
