### ISSUE TITLE
Implement Bookmarks.

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-frontend#215]
This issues addresses these: 
- Allows a user to easily add a question to their bookmarks
- Access their bookmarks from their profile page visible only to them.

**Comment by jomefavourite** [comment]
Could I please be pointed to the design, I couldn't find it

**Comment by devgenix** [comment]
I'm not sure the design is ready. I'm still waiting for it myself.

**Comment by devgenix** [comment]
@jomefavourite the design is available. I'll mention you there on Figma.

**Comment by devgenix** [comment]
> @jomefavourite the design is available. I'll mention you there on Figma.

I've done that now.
