### ISSUE TITLE
Integrate Univast

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-frontend#216]
This issue adds the ability to fetch data on tertiary institutions to be used on the educational information signup page.

**Comment by jomefavourite** [comment]
Okay, I'll work on it this week

**Comment by devgenix** [comment]
@jomefavourite 

You've been mailed an API Key to start working on this. Also, the docs have been updated and you should be able to get along with it fine. 

Check the Postman Workspace for the API Collection so you can test it. 

If you have anymore questions, reach out to me.

**Comment by jomefavourite** [comment]
> @jomefavourite
> 
> You've been mailed an API Key to start working on this. Also, the docs have been updated and you should be able to get along with it fine.
> 
> Check the Postman Workspace for the API Collection so you can test it.
> 
> If you have anymore questions, reach out to me.

Okay noted

**Comment by devgenix** [comment]
@jomefavourite let's finish this before the end of this sprint and move to #215 for the sprint task.

**Comment by devgenix** [comment]
All done by PR #227
