### ISSUE TITLE
Add redirect to original page on login from guest-mode

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-frontend#244]
If I visit Faraday through a link to a question/poll/article in guest mode and decide to comment/vote/reply, I'd be redirected to login from which I would either login if I have an account or signup. When I do that the link to the page where I was should be carried along and after a successful signup/login I should be taken back to the original page where I was. 

This can be done by holding the link to the page in a request parameter variable called redirect. 
So when I click to login from a discussion page in guest mode, I am taken to a login page and the URL of the login page would be something like; https://app-staging.faraday.africa/login?redirect=https://app-staging.faraday.africa/qfeed/a6474c2b-76b7-479c-8c9d-e323692b59be
If on that page I decide to signup instead,  it'd be; https://app-staging.faraday.africa/signup?redirect=https://app-staging.faraday.africa/qfeed/a6474c2b-76b7-479c-8c9d-e323692b59be

If you visit any of the links here, you'd be taken to the actual pages and see the redirect variable held in as a request parameter.  

From there up, it's up to you to then check after a successful signup/login if the URL was carrying a redirect and if was, redirect the user to the original page they were.

**Comment by devgenix** [comment]
@jomefavourite @nworiekingslee check this out. 
It's still in Backlogs for now.

**Comment by devgenix** [comment]
> Okay, I can do this

Alright. 

Let's round up on Bookmarks and improvements to Univast and then you can take this up.

**Comment by nworiekingslee** [comment]
Oops @jomefavourite I did this today. I didn't know you are taking it. It wasn't assigned. I found out after opening the issue

**Comment by jomefavourite** [comment]
> Oops @jomefavourite I did this today. I didn't know you are taking it. It wasn't assigned. I found out after opening the issue

No problem

**Comment by nworiekingslee** [comment]
Yes it is

**Comment by devgenix** [comment]
Good work. You can reference the PR that addressed this and close the issue
as completed.

**Comment by devgenix** [comment]
@nworiekingslee I've tried to test this but haven't seen the expected results. 

Can you demonstrate it in a video recording you'll share or in a video meeting?

**Comment by nworiekingslee** [comment]
Added a login button on the nav for guestmode

**Comment by nworiekingslee** [comment]
Oh. I just read the description of the issue. I apologize I have it mixed up

**Comment by devgenix** [comment]
> Oh. I just read the description of the issue. I apologize I have it mixed up

Alright. I'll assign this to @jomefavourite while you work on
