### ISSUE TITLE
Implement Qshot Redesign. 

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-frontend#276]
Find the new redesigned Qshot interface [here](https://www.figma.com/file/GmdqdKpgeXsuNo7WoF1xNq?node-id=2837:13694#439096738)

- [ ] Responsively implement the design that is titled "answered pen with background" to result in a single HTML file.

**Comment by jomefavourite** [comment]
I've done the layout, but this is the structure, do you need the asset and CSS to be in the HTML files

![image](https://github.com/faradayafrica/Faraday-frontend/assets/54733225/69a43307-953a-4a3c-8171-06c9ecd880e4)

**Comment by jomefavourite** [comment]
I've added all the files here, I did put the SVG in the HTML or Cloudinary, no time to do that now, bare with me

[qshot.zip](https://github.com/faradayafrica/Faraday-frontend/files/11488244/qshot.zip)
