### ISSUE TITLE
enhance edu signup-screen 

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-frontend#277]
In the third signup screen, which is used to collect academic data,

- [x] Add a Country Field.
       - Use the API Endpoint from Univast [here](https://univast.faraday.africa/api/auth/redocs/#tag/countries)
       - After getting the country from the Endpoint above, use the Country id from the data acquired from the response in the same endpoint above to make a POST request to fetch a list of Tertiary institutions in that Country. 
- [x] After collecting the data, add the country name obtained from the API Endpoint above and the school logo obtained from the data in the School response, to the data sent to the App Backend API. 
- [x] Use IDs instead of names and codes to get data for Schools, Faculties, and Departments.
- [x] In the POST request to the backend, pass the following data:
        - country name and country id
        - school name, school id, and school logo
        - faculty name and faculty id
        - department name and department id
        Check the Postman Workspace to see the exact variable names and required fields.

This issue depends on the following: 
- [x] [Univast](https://github.com/faradayafrica/Univast/issues/19) 
- [x] [App Backend API](https://github.com/faradayafrica/faradayapi/issues/243)

**Comment by jomefavourite** [comment]
> > Do all the tasks need to be done first before I work on them? Also, the Univast endpoint returned error on postman
> 
> Yes they have to. For the Univast Endpoint, we've fixed it. What is left is to re-upload the image so that it's now accessible.

Okay

**Comment by nworiekingslee** [comment]
I am on this
